spring.application.name=apfuckery
spring.jackson.default-property-inclusion=NON_NULL

apfuckery.url=https://apfuckery.remlit.site/

# INSTANCE ACTOR
instanceactor.username=blueb
instanceactor.displayName=evil harper
instanceactor.bio=this is my ultra evil account for evil ap fuckery... java powered.

instanceactor.avatarUrl=ia-avatar.png

instanceactor.isCat=true
instanceactor.speakAsCat=false